/** Declaration file generated by dts-gen */

export interface LintResult {
    column: number;
    file: string;
    fullPath: string;
    line: number;
    linter: string;
    message: string;
    position: number;
    severity: string;
    source: string;
}


export class Lesshint {
    constructor(...args: any[]);

    checkDirectory(...args: any[]): void;

    checkFile(...args: any[]): void;

    checkFiles(...args: any[]): void;

    checkPath(...args: any[]): void;

    checkString(...args: any[]): LintResult[];

    configure(...args: any[]): void;

    formatResults(...args: any[]): void;

    getConfig(...args: any[]): void;

    getReporter(...args: any[]): void;

    hasAllowedExtension(...args: any[]): void;

    isExcluded(...args: any[]): void;

}

export class Runner {
    constructor(...args: any[]);

    run(...args: any[]): void;

}


export namespace utils {
    function hasQuotes(str: any, style: any): any;

    function isAbsoluteURL(str: any): any;

    function isVariable(str: any): any;

    function parseSelector(selector: any): any;

    function parseValue(value: any, options: any): any;

    namespace parseSelector {
        const prototype: {
        };

    }

    namespace parseValue {
        const prototype: {
        };

    }

}

